---
# Form running gradle locally
server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:./h2/test
    platform: h2
    username: sa
    password:
  #    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    baseline-on-migrate: true




